import { ArrowRight } from "lucide-react";
import ContactForm from "../../components/ContactForm";

export default function ContactPage(){
  return <main>
    <section className="service-hero"><div className="shell service-hero-grid"><div><a href="/" className="service-back">← Nexusinn</a><div className="eyebrow">Contact</div><h1>Start with the business problem.<br/><span>We’ll map the capability.</span></h1><p className="lead">Whether you are evaluating a GCC, planning an AI program or modernizing insurance operations, the first step is understanding the operating context, constraints and outcomes you need.</p></div><div className="service-panel"><span className="service-panel-kicker">Conversation topics</span><div className="service-checks"><p>GCC strategy and operating model</p><p>AI readiness and enterprise roadmap</p><p>ML engineering and intelligent automation</p><p>Claims and underwriting modernization</p><p>InsurTech platform transformation</p><p>Responsible AI and governance</p></div></div></div></section>

    <section className="section contact-section"><div className="shell contact-layout">
      <div className="contact-copy"><div className="eyebrow">Talk to Nexusinn</div><h2>Tell us what you are trying to build or improve.</h2><p>Share enough context for the enquiry to reach the right capability area. Nexusinn can route requests across GCC, AI/ML and insurance technology based on the service interest selected.</p><div className="contact-notes"><div><b>Useful context</b><span>Business objective, current operating state, target timeline and important constraints.</span></div><div><b>Privacy-conscious</b><span>Please do not submit customer data, health information, policyholder records, credentials, secrets or other confidential material.</span></div><div><b>Enterprise routing</b><span>Your selected capability area is included with the enquiry so it can be directed to the appropriate Nexusinn conversation.</span></div></div><a className="link" href="/faq">Review common questions →</a></div>
      <div className="contact-card"><div className="contact-card-head"><span className="eyebrow">Business enquiry</span><h3>Discuss your initiative</h3><p>Required fields help us understand who is contacting Nexusinn and what capability you are evaluating.</p></div><ContactForm /></div>
    </div></section>

    <section className="section section-soft"><div className="shell service-two-col"><div><div className="eyebrow">Contact channel</div><h2>Lead delivery is environment-configured.</h2></div><div><p className="lead" style={{fontSize:16}}>The website now has a production-ready submission interface and validated API route. Public delivery activates when the deployment receives a secure <code>CONTACT_WEBHOOK_URL</code> pointing to the approved Nexusinn email, CRM, automation or lead-management endpoint.</p><p style={{color:"var(--muted)",lineHeight:1.7}}>This keeps credentials and vendor-specific integrations out of the public repository and prevents the site from claiming a successful submission when no destination exists.</p></div></div></section>
  </main>
}
