import { ArrowRight, Menu } from "lucide-react";

const values = [
  ["AI-First Approach", "Practical intelligence embedded into operations, decisions and customer journeys."],
  ["Regulatory Expertise", "Solutions designed with governance, auditability and regulated-industry needs in mind."],
  ["Global Delivery Network", "Build distributed capability without losing operating control or delivery visibility."],
  ["Risk & Compliance First", "Security, privacy and controls considered from architecture through operations."],
  ["Agile Scaling", "Start focused, validate value and expand teams and platforms with measurable milestones."],
  ["Domain-Specialized Talent", "Technology teams aligned to GCC, AI and insurance business contexts."],
  ["Long-Term Partnership", "Transformation support beyond implementation, from optimization to scale."],
  ["Data Security & Governance", "Clear data ownership, access controls and responsible AI foundations."],
];

export default function Home() {
  return (
    <main>
      <div className="topbar"><div className="shell"><span>Enterprise technology, global capability & insurance transformation</span><div className="socials"><span>LinkedIn</span><span>X</span><span>Instagram</span></div></div></div>
      <header className="nav"><div className="shell navinner"><a href="/" className="logo" aria-label="Nexusinn home"><span className="logo-mark" />Nexusinn</a><nav className="navlinks" aria-label="Main navigation"><a href="/gcc-solutions">GCC Solutions</a><a href="/ai-ml-services">AI & ML</a><a href="/insurance-solutions">Insurance</a><a href="#insights">Insights</a><a href="#careers">Careers</a><a href="#about">About</a></nav><div className="actions"><a className="btn btn-outline" href="#">Client Login</a><a className="btn btn-primary" href="#contact">Talk to an Expert <ArrowRight size={15}/></a><button className="btn btn-outline mobile-menu" aria-label="Open menu"><Menu size={20}/></button></div></div></header>
      <section className="hero"><div className="shell"><div className="hero-grid"><div><div className="eyebrow">Global capability. Intelligent execution.</div><h1>Build global advantage.<br/><span>Powered by intelligence.</span></h1><p className="lead">Nexusinn helps enterprises establish and scale Global Capability Centers, deploy AI and machine learning that delivers measurable outcomes, and modernize insurance operations with secure, compliant technology.</p><div className="hero-actions"><a href="#solutions" className="btn btn-primary">Explore Solutions <ArrowRight size={16}/></a><a href="#contact" className="btn btn-outline">Discuss Your Roadmap</a></div></div><div className="visual" aria-hidden="true"><div className="orb" /><div className="float-card fc1"><strong>Global Capability Centers</strong><span>Build · Operate · Transform · Scale</span></div><div className="float-card fc2"><strong>Enterprise AI</strong><span>Strategy · Automation · GenAI · ML</span></div><div className="float-card fc3"><strong>Insurance Technology</strong><span>Claims · Underwriting · Platforms</span></div></div></div><div className="stats"><div className="stat"><b>3</b><span>Integrated transformation pillars</span></div><div className="stat"><b>AI-first</b><span>Technology and operating mindset</span></div><div className="stat"><b>Global</b><span>Delivery designed for distributed enterprises</span></div></div></div></section>
      <section className="strip"><div className="shell strip-grid"><div className="strip-item"><b>Global Delivery Centers</b><p>Establish high-performance capability hubs with operating models built for scale.</p></div><div className="strip-item"><b>AI-Driven Automation</b><p>Turn repetitive processes and fragmented data into intelligent workflows.</p></div><div className="strip-item"><b>Insurance Technology</b><p>Modernize regulated workflows while preserving security, controls and explainability.</p></div></div></section>
      <section className="section" id="solutions"><div className="shell"><div className="section-head"><div className="eyebrow">What we do</div><h2>One partner across capability, intelligence and industry transformation.</h2><p>Nexusinn connects operating-model expertise with modern engineering. That means your GCC strategy, AI roadmap and insurance transformation can move together rather than becoming isolated initiatives.</p></div><div className="pillars"><article className="pillar" id="gcc"><div className="number">01</div><h3>GCC Solutions</h3><p>Design, launch and scale capability centers that become strategic extensions of your enterprise.</p><ul><li>Build-Operate-Transfer</li><li>Hybrid Captive Models</li><li>Joint Venture Models</li><li>Capability & operating model design</li></ul><a href="/gcc-solutions" className="link">Explore GCC Solutions →</a></article><article className="pillar" id="ai"><div className="number">02</div><h3>AI & ML Services</h3><p>Move from AI experimentation to governed, production-grade systems connected to real business outcomes.</p><ul><li>AI strategy & readiness</li><li>Model development & ML engineering</li><li>Intelligent automation</li><li>Generative AI integration</li></ul><a href="/ai-ml-services" className="link">Explore AI & ML →</a></article><article className="pillar" id="insurance"><div className="number">03</div><h3>Insurance Solutions</h3><p>Apply domain-aware technology to claims, underwriting, policy operations and compliance-intensive workflows.</p><ul><li>Claims automation</li><li>AI-assisted underwriting</li><li>InsurTech platforms</li><li>Compliance & regulatory technology</li></ul><a href="/insurance-solutions" className="link">Explore Insurance Solutions →</a></article></div></div></section>
      <section className="section section-soft" id="about"><div className="shell"><div className="section-head"><div className="eyebrow">Why Nexusinn</div><h2>Transformation designed for enterprise reality.</h2><p>Successful transformation requires more than technology. Nexusinn combines delivery strategy, specialized talent, AI engineering, governance and regulated-industry thinking into a single execution model.</p></div><div className="value-grid">{values.map(([title, text]) => <div className="value" key={title}><div className="dot"/><b>{title}</b><span>{text}</span></div>)}</div></div></section>
      <section className="section" id="insights"><div className="shell"><div className="section-head"><div className="eyebrow">Transformation stories</div><h2>Designed around measurable business outcomes.</h2><p>Our case-study framework focuses on the business problem, operating constraints, implementation model and measurable impact.</p></div><div className="case-grid"><article className="case"><div className="case-img"/><div className="case-body"><span className="case-label">Insurance · AI</span><h3>Accelerating claims workflows with intelligent automation</h3><p>A reference transformation pattern for reducing manual touchpoints while preserving review controls.</p><a className="link" href="/insurance-solutions/claims-automation">Explore claims automation →</a></div></article><article className="case"><div className="case-img"/><div className="case-body"><span className="case-label">GCC · Transformation</span><h3>Building a scalable global capability operating model</h3><p>A structured approach to capability design, talent, governance and progressive ownership transfer.</p><a className="link" href="/gcc-solutions">Explore GCC approach →</a></div></article><article className="case"><div className="case-img"/><div className="case-body"><span className="case-label">Underwriting · ML</span><h3>Operationalizing machine learning for better risk decisions</h3><p>A model lifecycle designed around data quality, explainability, deployment and continuous monitoring.</p><a className="link" href="/insurance-solutions/underwriting-ai">Explore underwriting AI →</a></div></article></div><div className="cta" id="contact"><h2>Build the next capability your business needs to compete.</h2><div className="hero-actions"><a className="btn btn-primary" href="#">Talk to Experts <ArrowRight size={16}/></a><a className="btn btn-outline" href="#solutions">Explore Solutions</a></div></div></div></section>
      <footer className="footer" id="careers"><div className="shell"><div className="footer-grid"><div><div className="logo" style={{color:"white"}}><span className="logo-mark"/>Nexusinn</div><p style={{fontSize:13,lineHeight:1.8,maxWidth:290}}>Global capability centers, enterprise AI and insurance technology — connected by one transformation mindset.</p></div><div><h4>GCC Solutions</h4><a href="/gcc-solutions/build-operate-transfer">Build-Operate-Transfer</a><a href="/gcc-solutions/hybrid-captive">Hybrid Captive</a><a href="/gcc-solutions/joint-venture">Joint Venture</a></div><div><h4>AI & ML</h4><a href="/ai-ml-services/ai-strategy">AI Strategy</a><a href="/ai-ml-services/intelligent-automation">Automation</a><a href="/ai-ml-services/generative-ai">Generative AI</a><a href="/ai-ml-services/responsible-ai">Responsible AI</a></div><div><h4>Insurance</h4><a href="/insurance-solutions/claims-automation">Claims</a><a href="/insurance-solutions/underwriting-ai">Underwriting</a><a href="/insurance-solutions/insurtech-platforms">InsurTech</a><a href="/insurance-solutions/compliance-regtech">Compliance</a></div><div><h4>Company</h4><a href="#about">About</a><a href="#insights">Insights</a><a href="#careers">Careers</a><a href="#contact">Contact</a></div></div><div className="footer-bottom"><span>© 2026 Nexusinn. All rights reserved.</span><span>Privacy · Terms · Responsible AI</span></div></div></footer>
    </main>
  );
}
