import { ArrowRight } from "lucide-react";

const values = [["AI-First Approach","Practical intelligence embedded into operations, decisions and customer journeys."],["Regulatory Expertise","Solutions designed with governance, auditability and regulated-industry needs in mind."],["Global Delivery Network","Build distributed capability without losing operating control or delivery visibility."],["Risk & Compliance First","Security, privacy and controls considered from architecture through operations."],["Agile Scaling","Start focused, validate value and expand teams and platforms with measurable milestones."],["Domain-Specialized Talent","Technology teams aligned to GCC, AI and insurance business contexts."],["Long-Term Partnership","Transformation support beyond implementation, from optimization to scale."],["Data Security & Governance","Clear data ownership, access controls and responsible AI foundations."]];

const images = {
  hero: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=85",
  claims: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1000&q=82",
  gcc: "https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1000&q=82",
  underwriting: "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1000&q=82",
};

export default function Home(){return <main>
<section className="hero"><div className="shell"><div className="hero-grid"><div><div className="eyebrow">Global capability. Intelligent execution.</div><h1>Build global advantage.<br/><span>Powered by intelligence.</span></h1><p className="lead">Nexusinn helps enterprises establish and scale Global Capability Centers, deploy AI and machine learning that delivers measurable outcomes, and modernize insurance operations with secure, compliant technology.</p><div className="hero-actions"><a href="#solutions" className="btn btn-primary">Explore Solutions <ArrowRight size={16}/></a><a href="/contact" className="btn btn-outline">Discuss Your Roadmap</a></div></div><div className="visual hero-art"><img src={images.hero} alt="Modern enterprise workspace representing global capability and digital transformation"/><div className="float-card fc1"><strong>Global Capability Centers</strong><span>Build · Operate · Transform · Scale</span></div><div className="float-card fc2"><strong>Enterprise AI</strong><span>Strategy · Automation · GenAI · ML</span></div><div className="float-card fc3"><strong>Insurance Technology</strong><span>Claims · Underwriting · Platforms</span></div></div></div><div className="stats"><div className="stat"><b>3</b><span>Integrated transformation pillars</span></div><div className="stat"><b>AI-first</b><span>Technology and operating mindset</span></div><div className="stat"><b>Global</b><span>Delivery designed for distributed enterprises</span></div></div></div></section>
<section className="strip"><div className="shell strip-grid"><div className="strip-item"><b>Global Delivery Centers</b><p>Establish high-performance capability hubs with operating models built for scale.</p></div><div className="strip-item"><b>AI-Driven Automation</b><p>Turn repetitive processes and fragmented data into intelligent workflows.</p></div><div className="strip-item"><b>Insurance Technology</b><p>Modernize regulated workflows while preserving security, controls and explainability.</p></div></div></section>
<section className="section" id="solutions"><div className="shell"><div className="section-head"><div className="eyebrow">What we do</div><h2>One partner across capability, intelligence and industry transformation.</h2><p>Nexusinn connects operating-model expertise with modern engineering. That means your GCC strategy, AI roadmap and insurance transformation can move together rather than becoming isolated initiatives.</p></div><div className="pillars"><article className="pillar"><div className="number">01</div><h3>GCC Solutions</h3><p>Design, launch and scale capability centers that become strategic extensions of your enterprise.</p><ul><li>Build-Operate-Transfer</li><li>Hybrid Captive Models</li><li>Joint Venture Models</li></ul><a href="/gcc-solutions" className="link">Explore GCC Solutions →</a></article><article className="pillar"><div className="number">02</div><h3>AI & ML Services</h3><p>Move from AI experimentation to governed, production-grade systems connected to real business outcomes.</p><ul><li>AI strategy & readiness</li><li>ML engineering</li><li>Intelligent automation</li></ul><a href="/ai-ml-services" className="link">Explore AI & ML →</a></article><article className="pillar"><div className="number">03</div><h3>Insurance Solutions</h3><p>Apply domain-aware technology to claims, underwriting and compliance-intensive workflows.</p><ul><li>Claims automation</li><li>AI-assisted underwriting</li><li>InsurTech platforms</li></ul><a href="/insurance-solutions" className="link">Explore Insurance Solutions →</a></article></div></div></section>
<section className="section section-soft"><div className="shell"><div className="section-head"><div className="eyebrow">Why Nexusinn</div><h2>Transformation designed for enterprise reality.</h2><p>Successful transformation requires more than technology. Nexusinn combines delivery strategy, specialized talent, AI engineering, governance and regulated-industry thinking.</p></div><div className="value-grid">{values.map(([title,text])=><div className="value" key={title}><div className="dot"/><b>{title}</b><span>{text}</span></div>)}</div></div></section>
<section className="section"><div className="shell"><div className="section-head"><div className="eyebrow">Transformation perspectives</div><h2>Designed around measurable business outcomes.</h2></div><div className="case-grid"><article className="case"><img className="case-img" src={images.claims} alt="Financial analytics representing insurance claims automation"/><div className="case-body"><span className="case-label">Insurance · AI</span><h3>Accelerating claims workflows with intelligent automation</h3><p>A reference transformation pattern for reducing manual touchpoints while preserving review controls.</p><a className="link" href="/insurance-solutions/claims-automation">Explore claims automation →</a></div></article><article className="case"><img className="case-img" src={images.gcc} alt="Modern enterprise office representing a scalable global capability center"/><div className="case-body"><span className="case-label">GCC · Transformation</span><h3>Building a scalable global capability operating model</h3><p>A structured approach to capability design, talent, governance and progressive ownership transfer.</p><a className="link" href="/gcc-solutions">Explore GCC approach →</a></div></article><article className="case"><img className="case-img" src={images.underwriting} alt="Advanced data and technology infrastructure representing machine learning underwriting"/><div className="case-body"><span className="case-label">Underwriting · ML</span><h3>Operationalizing machine learning for better risk decisions</h3><p>A model lifecycle designed around data quality, explainability, deployment and continuous monitoring.</p><a className="link" href="/insurance-solutions/underwriting-ai">Explore underwriting AI →</a></div></article></div><div className="cta"><h2>Build the next capability your business needs to compete.</h2><a className="btn btn-primary" href="/contact">Talk to an Expert <ArrowRight size={16}/></a></div></div></section>
<footer className="footer"><div className="shell"><div className="footer-grid"><div><img src="/api/brand-logo" alt="Nexusinn — Innovation, Talent, Impact" style={{display:"block",width:"min(100%,340px)",height:"auto"}}/><p style={{fontSize:13,lineHeight:1.8,maxWidth:290}}>Global capability centers, enterprise AI and insurance technology — connected by one transformation mindset.</p></div><div><h4>GCC Solutions</h4><a href="/gcc-solutions">Overview</a></div><div><h4>AI & ML</h4><a href="/ai-ml-services">Overview</a></div><div><h4>Insurance</h4><a href="/insurance-solutions">Overview</a></div><div><h4>Company</h4><a href="/about">About</a><a href="/insights">Insights</a><a href="/contact">Contact</a></div></div><div className="footer-bottom"><span>© 2026 Nexusinn. All rights reserved.</span><span>Privacy · Terms · Responsible AI</span></div></div></footer>
</main>}
